### PR TITLE
PR for responsive design project

### PR DESCRIPTION
**Pull request by bettercallazamat**
## In this project we managed to do the following:
1. Create navbar with fixed position
1.1. Necessary element pop-up and disappear on change of screen size
2. The main section is using grid
2.1. Background of the main sections are using gradient and background image
2.2. Responsiveness is applied for smaller screens
3. Changing display properties on elements
3.1. 3-4 column grid for wider than 1024, 3 column grid for less 
3.2. and 1 column for mobile or display block in some situations
4. Managed to create special bullet points on list elements
5. Almost none of the elements is using fixed width or height.

### CODE REVIEW

**Comment by majovanilla** [comment]
# Code Review in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey team, 👋

## Good job on this project! 👍

- Good Readme template
- Great Pull Request Message!

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors. Please fix them.
Screenshot from 2020-03-06 12-38-17

- Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it... And the scroll bar you have in the description is not the best way to go.

- The general layout of your page is wider than the original. Please adjust it.

**Navbar**

- The medium breakpoint should hide some elements of your navbar and include the TNW logo. Currently, your page breaks after the original, you don't hide one part, and the logo is larger. See the screenshot below.

Yours:
Screenshot from 2020-03-06 12-46-11

Original:
Screenshot from 2020-03-06 12-46-04

-  Check the small breakpoint and make the navbar behave the same. YOu are missing one black element to the left and the yellow banner should be taller.

YOurs:
Screenshot from 2020-03-06 12-52-42

Original:
Screenshot from 2020-03-06 12-52-37

**Three articles section**

- The section behaves well. Now fix the font-size to make it smaller in the medium breakpoint.
Yours:
Screenshot from 2020-03-06 12-55-57

Original:
Screenshot from 2020-03-06 12-55-51

**Categories section**

- It looks different from the original. If you already changed the width of the whole page, perhaps it will make it better. 

- You have a different style on the line that divides each bullet point and it is almost invisible. 
Yours:
Screenshot from 2020-03-06 13-02-54

Original:
Screenshot from 2020-03-06 13-03-10

**Latest deals**

- Your images are broken in this section, please fix them.
Screenshot from 2020-03-06 13-14-14

**Footer**

- Check the bottom section of the footer in all the breakpoints. The first and last logo have not the right size. 
Screenshot from 2020-03-06 13-15-59

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Your project would look sooo much better if you include the hover effects on the links of the page, like the original version.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] As the last TSE says: "...and the logo is larger...." the logo is still wider than the original page, consider fixing this.





[OPTIONAL]

- [ ] Consider adding the 'demo link in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Review by MarioDena — APPROVED** [review]
Hello! My name is Mario, congratulations on your project, I can see you've implemented the requested changes. Good job👍 

However previous reviewers failed to see that there are a lot of repeated rules on your code. take for example:

`linear-gradient(to top, rgba(0, 0, 0, 1) 0%, rgba(15, 15, 15, 0.66) 49%, rgba(15, 15, 15, 0.59) 59%, rgba(15, 15, 15, 0.54) 67%, rgba(15, 15, 15, 0.48) 75%, rgba(10, 10, 10, 0.41) 86%, rgba(99, 99, 99, 0.32) 98%, rgba(99, 99, 99, 0.31) 100%),` 

The above line is used 11 times on your project, along with other examples (`dsiplay`  and  `color` rules are repeated on your CSS file several times). It is very important you keep your code DRY (Don't Repeat Yourself). You can read the following article if you need more help. https://speckyboy.com/good-bad-css-practices/

## Optional Changes

- [ ] Consider fixing the repeated rules on your CSS. This change is supposed to be mandatory but as previous TSE's didn't mention it, this change is now optional, however I highly recommend you to implement the changes.

## This project is approved. 🏅 

## Code Review by Mario Enrique Delgado Naranjo

**Pull request merged**
